=== jmorille/ttstore/connector-ttbox/icecat-connector/icecat-supplier-jaxb-api/src/main/resources/ICECAT-supplier_mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ICECAT-interface">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SupplierMappings" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="SupplierMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Symbol" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="supplier_id" type="xs:int" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="SupplierMappings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SupplierMapping" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="Generated" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="Symbol">
    <xs:complexType mixed="true" />
  </xs:element>

</xs:schema>

=== jmorille/ttstore/connector-ttbox/icecat-connector/icecat-relations-jaxb-api/src/test/resources/supplier_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ICECAT-interface SYSTEM "http://data.icecat.biz/dtd/ICECAT-supplier_mapping.dtd">
<!-- source: ICEcat.biz 2010 -->
<ICECAT-interface xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://data.icecat.biz/xsd/ICECAT-supplier_mapping.xsd">
	<SupplierMappings Generated="20100331000501">
		<SupplierMapping supplier_id="1" name="HP">
			<Symbol>COMPAQ</Symbol>
			<Symbol>HP SUPPL</Symbol>
			<Symbol>HEWLETT PACKARD</Symbol>
			<Symbol>HP</Symbol>
			<Symbol>hp systems</Symbol>
			<Symbol>hp peripherals</Symbol>
			<Symbol>hp top value</Symbol>
			<Symbol>hp supplies</Symbol>
			<Symbol>Compaq Spare Parts</Symbol>
			<Symbol>HP Spare Parts</Symbol>
			<Symbol>CQ</Symbol>
			<Symbol>HPQDESKT</Symbol>
			<Symbol>COMPAQ-SPARE</Symbol>
			<Symbol>HPQNOTEB</Symbol>
			<Symbol>HP MULTI</Symbol>
			<Symbol>HPTON</Symbol>
			<Symbol>HPQWRKST</Symbol>
			<Symbol>HP DIGPR</Symbol>
			<Symbol>HPQHANDH</Symbol>
			<Symbol>HPINK</Symbol>
			<Symbol>HP LASCO</Symbol>
			<Symbol>HPQOPTIO</Symbol>
			<Symbol>HP 9000</Symbol>
			<Symbol>HPQSTORA</Symbol>
			<Symbol>HP OVERIG</Symbol>
			<Symbol>HPCINKJT</Symbol>
			<Symbol>HEWLETT-PACKARD</Symbol>
			<Symbol>SUNSET</Symbol>
			<Symbol>COMPAQ HP PSG</Symbol>
			<Symbol>COMPAQ HP PROJECTOR</Symbol>
			<Symbol>COMPAQ HP ALPHA SERVERS</Symbol>
			<Symbol>COMPAQ HP SERVICES</Symbol>
			<Symbol>COMPAQ HP OUTSOURCED</Symbol>
			<Symbol>COMPAQ HP SERVERS</Symbol>
			<Symbol>COMPAQ HP STORAGE</Symbol>
			<Symbol>PART OF HP</Symbol>
			<Symbol>COMPAQ COMPUTER</Symbol>
			<Symbol>Q7311A#ABH</Symbol>
			<Symbol>HP STORAGE MEDIA BY IMATION HPUN</Symbol>
			<Symbol>HP _ UNREPORTED SPARE PARTS</Symbol>
			<Symbol>HP STORAGE MEDIA BY IMATION HPUNREP</Symbol>
			<Symbol>GENUINE HEWLETT-PACKARD</Symbol>
			<Symbol>HP IP</Symbol>
			<Symbol>COMPAQ SMARTSTART</Symbol>
			<Symbol>HP üBRIG</Symbol>
			<Symbol>HP NETWOKING</Symbol>
			<Symbol>HP SPECIAL</Symbol>
			<Symbol>HP ?BRIG</Symbol>
			<Symbol>HP Openview</Symbol>
			<Symbol>HEWLETT-PACKARD STORAGE</Symbol>
			<Symbol>COMPAQ COMPUTER LIMITED</Symbol>
			<Symbol>HP SERVER ISS</Symbol>
			<Symbol>HEWLETT PACKARD BV</Symbol>
			<Symbol>HP PRINTSERVER</Symbol>
			<Symbol>HP UNIX SYSTEM</Symbol>
			<Symbol>HP-CONSUMIBLES</Symbol>
			<Symbol>HP/COMPAQ</Symbol>
			<Symbol>HP SPARES</Symbol>
			<Symbol>HP HEWLETT PACKARD</Symbol>
			<Symbol>HEWLETT PACKARD / HP</Symbol>
			<Symbol>HPSUPPLIES</Symbol>
			<Symbol>HP WORKSTATIONS</Symbol>
			<Symbol>HP SERVERS</Symbol>
			<Symbol>HP PCS</Symbol>
			<Symbol>HP NETWORK</Symbol>
			<Symbol>HP MOBILE</Symbol>
			<Symbol>HP HANDHELD</Symbol>
			<Symbol>HP MEDIASMART</Symbol>
			<Symbol>HP ISS</Symbol>
			<Symbol>HP HOME</Symbol>
			<Symbol>HP HARDWARE</Symbol>
			<Symbol>HP CONSUMABLES</Symbol>
			<Symbol>HP COMPUTERS</Symbol>
			<Symbol>HP COMMERCIAL</Symbol>
			<Symbol>HP CALCULATORS</Symbol>
			<Symbol>HP BUSINESS</Symbol>
			<Symbol>HEWLETT-PACKARD CO.</Symbol>
			<Symbol>HEWLETT PACKARD FINANCE LTD.</Symbol>
			<Symbol>HP COMPUTER PSG</Symbol>
			<Symbol>HP-PCS-PROFESIONAL</Symbol>
			<Symbol>HP-PORTATILES</Symbol>
			<Symbol>HEWLETT-PACKARD OEM</Symbol>
			<Symbol>HEWLETT PACKARD LTD</Symbol>
			<Symbol>HEWLETT PA</Symbol>
			<Symbol>HP HEWLETT PACKARD SUPPLIES</Symbol>
			<Symbol>HEWLETT PACKARD TRAINING</Symbol>
			<Symbol>HP HEWLETT PACKARD NETWORKING</Symbol>
			<Symbol>HP THIN CLIENTS</Symbol>
			<Symbol>HP STORAGE</Symbol>
			<Symbol>HP_WKS_TFIG</Symbol>
			<Symbol>HP - *</Symbol>
			<Symbol>HP EXTENSION GAR PC</Symbol>
			<Symbol>HP RETAIL</Symbol>
			<Symbol>HP SUPPL TONER</Symbol>
			<Symbol>HP-COMPAQ PR</Symbol>
			<Symbol>HEWLETT PACKARD PROCURVE</Symbol>
			<Symbol>HP-COMPAQ GP</Symbol>
			<Symbol>HEWLET PACKARD SPARE</Symbol>
			<Symbol>HEWLETT PACKARD £ (UK)</Symbol>
			<Symbol>HP-PCS-CONSUMO</Symbol>
			<Symbol>HEWLETT PACKARD LIMITED</Symbol>
			<Symbol>HP DIREKT</Symbol>
			<Symbol>HP AFRICA</Symbol>
			<Symbol>HEWLETT PACKARD MEXICO S DE RL CV</Symbol>
			<Symbol>HP SCAN</Symbol>
			<Symbol>HP COMPAQ</Symbol>
			<Symbol>HP HEWLETT-PACKARD</Symbol>
			<Symbol>HEWLETT PACKARD MEXICO STORAGE II</Symbol>
			<Symbol>HP-MONITORES</Symbol>
			<Symbol>HP-PCS-WORKSTATION</Symbol>
			<Symbol>HEWLETT PACKARD MEXICO SRL DE CV</Symbol>
			<Symbol>HEWLATT PACKARD</Symbol>
			<Symbol>HEWLETT</Symbol>
			<Symbol>HEWLETT-PACKARD DE MEXICO</Symbol>
			<Symbol>HP-THINCLIENT</Symbol>
			<Symbol>HEWLETT PACKARD MEXICO</Symbol>
			<Symbol>HP HEWLETT PACKARD STORAGE</Symbol>
			<Symbol>HP TSG</Symbol>
			<Symbol>HP-ACCESORIOS</Symbol>
			<Symbol>HEWLETT PACKARD MEXICO S DE R.L.</Symbol>
			<Symbol>HEWLETT PACKARD DE MEXICO</Symbol>
			<Symbol>HP COMPAQ 6910, 6910P SERIES</Symbol>
			<Symbol>HP HDX X16 X16T HDX16 SERIES</Symbol>
			<Symbol>HP STORAGE VALUE</Symbol>
			<Symbol>HP PAVILION DV3-2000 SERIES</Symbol>
			<Symbol>HP HDX X18 X18T</Symbol>
			<Symbol>HEWLETT PACKARD S.A DE C.V</Symbol>
			<Symbol>HP COMPAQ TX1000 TX1300 TX1100</Symbol>
			<Symbol>HP PAVILION DV6 DV6-1000 DV6-1</Symbol>
		</SupplierMapping>
		<SupplierMapping supplier_id="2" name="Toshiba">
			<Symbol>TOSHIBA</Symbol>
			<Symbol>TOSHANDH</Symbol>
			<Symbol>TOSCNOTE</Symbol>
			<Symbol>TOSNOTEB</Symbol>
			<Symbol>TOSHIBA BEAMERS</Symbol>
			<Symbol>TOSHIBA BEAMER</Symbol>
			<Symbol>TOSHIBA SPECIAL</Symbol>
			<Symbol>TOSHIBA COMPUTER</Symbol>
			<Symbol>TSH</Symbol>
			<Symbol>TOSHIBA AUDIO-VIDEO</Symbol>
			<Symbol>TOSHIBA HARD DRIVES</Symbol>
			<Symbol>TOSHIBA CONSUMER</Symbol>
			<Symbol>TOSHIBA CONSUMER (TV/DVD/ETC)</Symbol>
			<Symbol>TOSHIBA CAMERAS</Symbol>
			<Symbol>TOSHIBASURF</Symbol>
			<Symbol>TOSHIBA-CONSUMIBLES</Symbol>
			<Symbol>TOSHIBA UK</Symbol>
			<Symbol>TOSHIBA - *</Symbol>
			<Symbol>TOSHIBA TEC</Symbol>
			<Symbol>TOSHIBA TECH</Symbol>
			<Symbol>TOSHIBA DE MEXICO, S.A. DE C.V.</Symbol>
			<Symbol>TOSHIBA INFORMATION SYS (UK) LT</Symbol>
			<Symbol>TOSHIBA P2000 U200 SERIES</Symbol>
			<Symbol>TOSHIBA HD</Symbol>
			<Symbol>TOSHIBA DE MEXICO S.A. DE C.V.</Symbol>
			<Symbol>TOSHIBA SATELLITE A200 A205 A2</Symbol>
			<Symbol>TOSHIBA INFORMATION SYS (UK) LTD</Symbol>
			<Symbol>TOSHIBA DE MEXICO  S.A. DE C.V.</Symbol>
		</SupplierMapping>
		<SupplierMapping supplier_id="3" name="IBM">
			<Symbol>IBM FOCUS</Symbol>
			<Symbol>IBM</Symbol>
			<Symbol>LOTUS DEVELOPMENT</Symbol>
			<Symbol>IBM STORAGE</Symbol>
			<Symbol>IBM Printing Systems</Symbol>
			<Symbol>LOTUS</Symbol>
			<Symbol>IBM SOFTWARE</Symbol>
			<Symbol>IBMPCC</Symbol>
			<Symbol>IBM RS/6000</Symbol>
			<Symbol>IBM AS/400</Symbol>
			<Symbol>LOTUS / IBM</Symbol>
			<Symbol>IBM RS/6000 I'P</Symbol>
			<Symbol>IBM DIVERSEN</Symbol>
			<Symbol>IBM OPTIONS OTHERS</Symbol>
			<Symbol>IBM PRINTERSUPPLIES</Symbol>
			<Symbol>IBM Opslagmedia</Symbol>
			<Symbol>IB</Symbol>
			<Symbol>IBM SPECIAL</Symbol>
			<Symbol>TIVOLI SOFTWARE</Symbol>
			<Symbol>WEBSPHERE SOFTWARE</Symbol>
			<Symbol>LOTUS SOFTWARE</Symbol>
			<Symbol>IBM X SERIES STORAGE</Symbol>
			<Symbol>IBM DATA MANAGEMENT</Symbol>
			<Symbol>IBM PRINTER SUPPLIES</Symbol>
			<Symbol>IBM STORAGE MEDIA</Symbol>
			<Symbol>IBM WEBSPHERE</Symbol>
			<Symbol>TIVOLI</Symbol>
			<Symbol>IBM (UK) LTD</Symbol>
			<Symbol>IBM OPENPOWER</Symbol>
			<Symbol>IBM STORAG</Symbol>
			<Symbol>IBM XSERIES 440</Symbol>
			<Symbol>IBM RISC/6000 &amp; STORAGE</Symbol>
			<Symbol>IBM - *</Symbol>
			<Symbol>IBM DE MEXICO COM Y SERVICIOS S.A.</Symbol>
			<Symbol>IBM COMPUTER</Symbol>
		</SupplierMapping>
		<SupplierMapping supplier_id="5" name="Sony">
			<Symbol>SONY</Symbol>
			<Symbol>Sony Data Media</Symbol>
			<Symbol>Sony Information Products</Symbol>
			<Symbol>Sony Presentatie</Symbol>
			<Symbol>Sony Storage</Symbol>
			<Symbol>Sony Vaio</Symbol>
			<Symbol>SONDIGCA</Symbol>
			<Symbol>SON DVD</Symbol>
			<Symbol>SONDIGPR</Symbol>
			<Symbol>SONPCC</Symbol>
			<Symbol>SONOPT</Symbol>
			<Symbol>SONCSTOR</Symbol>
			<Symbol>SONY OPTICAL</Symbol>
			<Symbol>SONY TAPE</Symbol>
			<Symbol>SONY CONSUMER ELECTRONICS</Symbol>
			<Symbol>SONY OPTICAL RETAIL</Symbol>
			<Symbol>SO</Symbol>
			<Symbol>SONY MONITORS</Symbol>
			<Symbol>SONY OPTICAL OEM</Symbol>
			<Symbol>SONY NORDIC</Symbol>
			<Symbol>SONY SPECIAL</Symbol>
			<Symbol>SONY UNITED KINGDOM LIMITED.</Symbol>
			<Symbol>SONY-NEC</Symbol>
			<Symbol>SONY NEC OPTIARC</Symbol>
			<Symbol>SONY/NEC OPTIARC</Symbol>
			<Symbol>SONY-MULTIMEDIA</Symbol>
			<Symbol>SONY UNITED KINGDOM LTD</Symbol>
			<Symbol>SONY (UK) LTD</Symbol>
			<Symbol>SONY-OPCIONES</Symbol>
			<Symbol>SONY STYLE EUROPE</Symbol>
			<Symbol>SONY-TV</Symbol>
			<Symbol>SONY-CONSUMIBLES</Symbol>
			<Symbol>SONY STORAGE &amp; MEDIA</Symbol>
			<Symbol>SONY-ALMACENAMIENTO</Symbol>
			<Symbol>SONY DIGITAL VIDEO</Symbol>
			<Symbol>SONY MEDIA</Symbol>
			<Symbol>SONY VAIO HIGH END</Symbol>
			<Symbol>OPTIARC</Symbol>
			<Symbol>NEC SONY OPTIARC</Symbol>
			<Symbol>SONY/</Symbol>
			<Symbol>SONY SES</Symbol>
			<Symbol>SONY UK LTD</Symbol>
			<Symbol>SONY NEC OPTIARC EUROPE</Symbol>
			<Symbol>SONY SUPPLIES</Symbol>
			<Symbol>SONYSTOR</Symbol>
			<Symbol>SONY-PORTATILES</Symbol>
			<Symbol>SONY OPTIARC EUROPE</Symbol>
			<Symbol>SONY-CAMARAS-DIGITALES</Symbol>
			<Symbol>SONY-IPELA</Symbol>
			<Symbol>SONY CREATIVE SOFTWARE</Symbol>
			<Symbol>SONY-PROYECTORES</Symbol>
			<Symbol>SONY-OPCIONES-PORTATIL</Symbol>
			<Symbol>SONY-NEC-OPTIARC</Symbol>
			<Symbol>SONY PRO</Symbol>
			<Symbol>SONY PHOTO VIDEO</Symbol>
			<Symbol>SONY MULTIMEDIA</Symbol>
			<Symbol>SONYOTH</Symbol>
			<Symbol>SONYRET</Symbol>
			<Symbol>SONY BATT.</Symbol>
			<Symbol>SONY PILES</Symbol>
			<Symbol>SONY HARDWARE</Symbol>
			<Symbol>GPS SONY</Symbol>
			<Symbol>SONY - *</Symbol>
